app/interface/__init__.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/25 9:25
# @Author : Gery.li
# @File : __init__.py.py
from flask import Blueprint

interface = Blueprint("interface", __name__)
from . import views

app/interface/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/26 9:21
# @Author : Gery.li
# @File : views.py
from datetime import datetime

from flask_login import current_user, login_required

from app.forms import InterfaceForm, InterfaceSearchForm
from . import interface
from flask import render_template, g, request, flash, redirect, url_for
from app.models import Interface
from sqlalchemy import and_
from exts import db

select = "接口管理"


@interface.route("/interface/list", methods=["GET", "POST"])
@login_required
def interface_list():
    form = InterfaceSearchForm()
    interfaces = Interface.query.filter(Interface.creater_id == current_user.id).order_by(Interface.update_time.desc())
    if request.method == "POST" and form.validate_on_submit():
        name = form.name.data
        uri = form.uri.data
        service = form.service.data

        if name:
            interfaces = [interface for interface in interfaces if interface.name.find(name) != -1]
            form.name.data = form.name.data
        if uri:
            interfaces = [interface for interface in interfaces if interface.uri.find(uri) != -1]
            form.uri.data = form.uri.data
        if service:
            interfaces = [interface for interface in interfaces if interface.service_id == service]
            form.service.data = form.service.data
    return render_template("interface/list.html", interfaces=interfaces, form=form, select=select)


@interface.route("/interface/<id>/info", methods=["GET", "POST"])
@login_required
def interface_info(id):
    form = InterfaceForm()
    interface = Interface.query.filter(and_(Interface.id == id, Interface.creater_id == current_user.id)).first()
    if interface:
        if request.method == "POST" and form.validate_on_submit():
            interface.name = form.name.data
            interface.uri = form.uri.data
            interface.method = form.method.data
            interface.headers = form.headers.data
            interface.body = form.body.data
            interface.service_id = form.service.data
            interface.desc = form.desc.data
            interface.update_time = datetime.now()
            db.session.commit()
            return redirect(url_for(".interface_list"))
        else:
            form.name.data = interface.name
            form.uri.data = interface.uri
            form.method.data = interface.method
            form.headers.data = interface.headers
            form.body.data = interface.body
            form.service.data = interface.service_id
            form.desc.data = interface.desc
        return render_template("interface/info.html", form=form, id=id, select=select)
    else:
        return


@interface.route("/interface/create/", methods=["GET", "POST"])
@login_required
def interface_create():
    form = InterfaceForm()
    if request.method == "POST" and form.validate_on_submit():
        interface = Interface()
        interface.name = form.name.data
        interface.uri = form.uri.data
        interface.method = form.method.data
        interface.headers = form.headers.data
        interface.body = form.body.data
        interface.service_id = form.service.data
        interface.desc = form.desc.data
        interface.creater_id = current_user.id
        interface.create_time = datetime.now()
        interface.update_time = datetime.now()
        interface.env_type = "测试环境"
        db.session.add(interface)
        db.session.commit()
        return redirect(url_for(".interface_list"))
    else:
        return render_template("interface/add.html", form=form, select=select)

app/templates/interface/add.html
{% extends 'base_ext.html' %}
{% block title %}新建接口{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('interface.interface_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
    </div>
    <div class="info-body">
        <form action="{{ url_for('interface.interface_create') }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>

{% endblock %}

app/templates/interface/info.html
{% extends 'base_ext.html' %}
{% block title %}接口详情{% endblock %}
{% block head %}
        <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('interface.interface_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
    </div>
    <div class="info-body">
        <form action="{{ url_for('interface.interface_info',id=id) }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/interface/list.html
{% extends 'base_ext.html' %}
{% block title %}接口一览{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-list.css') }}">
{% endblock %}
{% block main %}
    <div class="list-top">
        <div class="list-top-search">
            <form class="navbar-form navbar-left" role="search" action="{{ url_for('interface.interface_list') }}"
                  method="post">
                {{ wtf.quick_form(form) }}
            </form>
        </div>
        <div class="list-top-func-btn">
            <li>
                <a href="{{ url_for('interface.interface_create') }}">
                    <button type="submit" class="btn btn-primary">新建接口</button>
                </a>
            </li>
        </div>
    </div>
    <div class="list-body">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                {% for th in ["编号","所属服务","接口名称","接口路径","请求方式","接口描述","更新时间"] %}
                    <th>{{ th }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for interface in interfaces %}
                <tr class="tr-td">
                    <td class="td">{{ interface.id }}</td>
                    <td class="td"><a
                            href="{{ url_for('services.service_info',id=interface.service.id) }}">{{ interface.service.name }}</a>
                    </td>
                    <td class="td">{{ interface.name }}</td>
                    <td class="td">{{ interface.uri }}</td>
                    <td class="td">{{ interface.method }}</td>
                    <td class="td">{{ interface.desc if interface.desc  else "" }}</td>
                    <td class="td">{{ interface.update_time }}</td>
                    <td>
                        <form action="{{ url_for('interface.interface_info',id=interface.id) }}" class="form-container">
                            <button class="btn btn-primary">详情</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}