app/services/__init__.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/26 10:00
# @Author : Gery.li
# @File : __init__.py.py

from flask import Blueprint

services = Blueprint("services", __name__)
from . import views

app/services/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/26 10:01
# @Author : Gery.li
# @File : views.py
from datetime import datetime
from operator import and_

from flask import render_template, redirect, url_for, g, request, flash
from sqlalchemy import and_
from app.models import Service
from app.forms import ServiceForm
from exts import db
from flask_login import login_required, current_user

from . import services

select = "服务管理"


@services.route("/service/list")
@login_required
def service_list():
    name = request.args.get("name")
    host = request.args.get("host")
    user_id = current_user.id
    if name and host:
        search = and_(Service.creater_id == user_id, Service.name.contains(name),
                      Service.host.contains(host))
    elif name:
        search = and_(Service.creater_id == user_id, Service.name.contains(name))
    elif host:
        search = and_(Service.creater_id == user_id, Service.host.contains(host))
    else:
        search = and_(Service.creater_id == user_id)
    services = Service.query.filter(search).order_by(Service.update_time.desc())
    return render_template("services/list.html", services=services, select=select)


@services.route("/services/<id>/info", methods=["GET", "POST"])
@login_required
def service_info(id):
    form = ServiceForm()
    service = Service.query.filter(and_(Service.id == id)).first()
    if service:
        if request.method == "POST" and form.validate_on_submit():
            service.name = form.name.data
            service.protocol = form.protocol.data
            service.host = form.host.data
            service.port = form.port.data
            service.desc = form.desc.data
            service.update_time = datetime.now()
            db.session.commit()
            return redirect(url_for(".service_list"))
        form.name.data = service.name
        form.host.data = service.host
        form.port.data = service.port
        form.desc.data = service.desc
        form.protocol.data = service.protocol
        return render_template("services/info.html", form=form, id=id, select=select)
    flash("查看的服务不存在，请重试")
    return redirect(url_for(".service_list"))


@services.route("/service/create/", methods=["GET", "POST"])
@login_required
def service_create():
    form = ServiceForm()
    if request.method == "POST" and form.validate_on_submit():
        service = Service()
        service.name = form.name.data
        service.host = form.host.data
        service.port = form.port.data
        service.desc = form.desc.data
        service.protocol = form.protocol.data
        service.creater_id = current_user.id
        service.create_time = datetime.now()
        service.update_time = datetime.now()
        try:
            db.session.add(service)
            db.session.commit()
        except Exception as e:
            flash("创建服务失败，请重试")
        return redirect(url_for(".service_list"))
    return render_template("services/add.html", form=form, select=select)

app/templates/services/add.html
{% extends 'base_ext.html' %}
{% block title %}新建应用{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('services.service_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
    </div>
    <div class="info-body">
        <form action="{{ url_for('services.service_create') }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/services/info.html
{% extends 'base_ext.html' %}
{% block title %}服务详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('services.service_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
    </div>
    <div class="info-body">
        <form action="{{ url_for('services.service_info',id=id) }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>

{% endblock %}

app/templates/services/list.html
{% extends 'base_ext.html' %}
{% block title %}应用一览{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-list.css') }}">
{% endblock %}
{% block main %}
    <div class="list-top clearfix">
        <div class="list-top-search">
            <form class="navbar-form navbar-left" role="search" action="{{ url_for('services.service_list') }}">
                <div class="form-group">
                    <label class="control-label" for="name">应用名称：</label>
                    <input type="text" class="form-control" name="name" placeholder="请输入"/>
                </div>
                <div class="form-group">
                    <label class="control-label" for="host">应用地址：</label>
                    <input type="text" class="form-control" name="host" placeholder="请输入"/>
                </div>

                <div class="form-group btn-right">
                    <button type="submit" class="btn btn-primary">搜索</button>
                </div>
            </form>
        </div>
        <div class="list-top-func-btn">
            <li>
                <a href="{{ url_for('services.service_create') }}">
                    <button type="submit" class="btn btn-primary">新建应用</button>
                </a>
            </li>
        </div>
    </div>
    <div class="list-body">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                {% for th in ["编号","应用名称","协议","应用地址","应用端口","应用描述","更新时间"] %}
                    <th>{{ th }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for service in services %}
                <tr class="tr-td">
                    <td class="td">{{ service.id }}</td>
                    <td class="td">{{ service.name }}</td>
                    <td class="td">{{ service.protocol }}</td>

                    <td class="td">{{ service.host }}</td>
                    <td class="td">{{ service.port if service.port != None else "" }}</td>
                    <td class="td">{{ service.desc }}</td>
                    <td class="td">{{ service.update_time }}</td>
                    <td>
                        <form action="{{ url_for('services.service_info',id=service.id) }}" class="form-container">
                            <button class="btn btn-primary">详情</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}