app/user/__init__.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/25 9:25
# @Author : Gery.li
# @File : __init__.py.py
from flask import Blueprint

user = Blueprint("user", __name__)
from . import views

app/user/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/25 9:33
# @Author : Gery.li
# @File : views.py
from flask import render_template, redirect, \
    request, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from app.forms import SignForm, LoginForm
from app.models import User
from common.Constant import FlashEnum
from . import user
from exts import db


@user.route("/user/sign/", methods=["GET", "POST"])
def sign():
    # form = SignForm()
    # if request.method == "POST" and form.validate_on_submit():
    if request.method == "POST":
        telephone = request.form.get("telephone")
        mini_name = request.form.get("mini_name")
        password = request.form.get("password")
        email = request.form.get("email")
        new_user = User(telephone=telephone, mini_name=mini_name, password=password, email=email)
        try:
            db.session.add(new_user)
            db.session.commit()
        except:
            flash("注册用户失败",FlashEnum.warning.name)
        return redirect(url_for('.login'))
    return render_template("user/user.html")


@user.route("/user/login/", methods=["GET", "POST"])
def login():
    # form = LoginForm()
    if request.method == "POST":
        telephone = request.form.get("telephone")
        password = request.form.get("password")
        remember = request.form.get("remember")
        user_info = User.query.filter(User.telephone == telephone).first()

        if user_info and user_info.check_password(password):
            login_user(user_info, remember)
            next = request.args.get("next")
            if next is None or not next.startswith("/"):
                next = url_for("index")
                return redirect(next)
        flash("用户不存在或密码错误！", FlashEnum.warning.name)
    return render_template("user/user.html")


@user.route("/logout/")
@login_required
def logout():
    logout_user()
    flash("退出成功", FlashEnum.success.name)
    return redirect(url_for(".login"))

# @user.before_app_request
# def before_request():
#     g.user = current_user


# @user.context_processor
# def context_processor():
#     if hasattr(g, 'user'):
#         return {"user_info": g.user}
#     return {}

app/templates/user/login.html
{% extends 'base.html' %}
{% block title %}登陆{% endblock %}
{% block head %}
{#    <link rel="stylesheet" href="{{ url_for('static',filename='css/login.css') }}">#}
{% endblock %}
{% block main %}
    <div class="content-box-40">
        <h3 class="page-title">登陆</h3>
        <form action="{{ url_for('user.login') }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>

{% endblock %}

app/templates/user/sign.html
{% extends 'base.html' %}
{% block title %}知了-注册{% endblock %}
{% block head %}
    {#    <link rel="stylesheet" href="{{ url_for('static',filename='css/sign.css') }}">#}
{% endblock %}

{% block main %}
    <div class="content-box-40">
        <h3 class="page-title">注册</h3>
        <form action="{{ url_for('user.sign') }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/user/user.html
{% extends 'base.html' %}
{% block title %}登陆{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">
    <script src="{{ url_for('static',filename='js/user.js') }}"></script>
{% endblock %}
{% block main %}
    <section id="content">
        {#===============头部======================#}
        <div class="content-header clearfix">
            <a class='current' href="javascript:">我要登陆</a>
            <a href="javascript:">我要注册</a>
        </div>

        {#===============内容======================#}
        <div class="content-body">
            <div class="dom current">
                <form action="{{ url_for('user.login') }}" method="post">
                    <div class="form-group  required">
                        <label class="control-label" for="telephone"><em>*</em>手机号码</label>
                        <input class="form-control" id="telephone" name="telephone" required="" type="text" value="">
                    </div>
                    <div class="form-group  required">
                        <label class="control-label" for="password"><em>*</em>密码</label>
                        <input class="form-control" id="password" name="password" required="" type="password" value="">

                    </div>
                    <div class="checkbox">
                        <label>
                            <input id="remember" name="remember" type="checkbox" value="y"> 记住我
                        </label>
                    </div>
                    <input class="btn btn-default btn-primary btn-block" id="submit" name="submit" type="submit"
                           value="立即登陆">
                </form>
            </div>

            <div class="dom">
                <form action="{{ url_for('user.sign') }}" method="post">
                    <div class="form-container">
                        <div class="form-group  required">
                            <label class="control-label" for="telephone"><em>*</em>手机号码</label>
                            <input class="form-control" id="telephone" name="telephone" placeholder="手机号码" required=""
                                   type="text" value="">
                        </div>
                        <div class="form-group  required">
                            <label class="control-label" for="mini_name"><em>*</em>昵称</label>
                            <input class="form-control" id="mini_name" name="mini_name" required="" type="text"
                                   value="">
                        </div>
                        <div class="form-group  required">
                            <label class="control-label" for="email"><em>*</em>电子邮箱</label>
                            <input class="form-control" id="email" name="email" required="" type="text" value="">
                        </div>
                        <div class="form-group  required">
                            <label class="control-label" for="password"><em>*</em>密码</label>
                            <input class="form-control" id="password" name="password" required="" type="password"
                                   value="">
                        </div>
                        <div class="form-group  required">
                            <label class="control-label" for="re_password"><em>*</em>重复密码</label>
                            <input class="form-control" id="re_password" name="re_password" required="" type="password"
                                   value="">
                        </div>
                        <input class="btn btn-default btn-primary btn-block" id="submit" name="submit" type="submit"
                               value="立即注册">
                    </div>
                </form>

            </div>
        </div>


    </section>

{% endblock %}