app/case/__init__.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/25 9:25
# @Author : Gery.li
# @File : __init__.py.py
from flask import Blueprint

case = Blueprint("case", __name__)
from . import views

app/case/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/8/25 18:21
# @Author : Gery.li
# @File : views.py
from datetime import datetime
from flask import render_template, request, url_for, g, redirect, flash
from exts import db
from . import case
from app.models import Case, Interface
from app.forms import CaseForm, CaseSearchForm, CaseAddForm
from common.CaseRun import CaseRun
from flask_login import login_required, current_user
from common.Constant import FlashEnum

select = "用例管理"
case_run = CaseRun()


@case.route("/case/list", methods=["GET", "POST"])
@login_required
def case_list():
    form = CaseSearchForm()
    cases = Case.query.filter(Case.creater_id == current_user.id).order_by(Case.update_time.desc())
    if request.method == "POST" and form.validate_on_submit():
        service = form.service.data
        interface = form.interface.data
        name = form.name.data
        if name:
            cases = [case for case in cases if case.name.find(name) != -1]
        if service:
            cases = [case for case in cases if case.service_id == service]
        if interface:
            cases = [case for case in cases if case.interface_id == interface]
        form.service.data = form.service.data
        form.interface.data = form.interface.data
        form.name.data = form.name.data
    return render_template("case/list.html", cases=cases, form=form, select=select)


@case.route("/case/<id>/info", methods=["GET", "POST"])
@login_required
def case_info(id):
    form = CaseForm()
    case = Case.query.filter(Case.id == id).first()
    if case:
        if request.method == "POST" and form.validate_on_submit():
            interface = Interface.query.filter(Interface.id == form.interface.data).first()
            case.interface = interface
            case.service = interface.service
            case.name = form.name.data
            case.is_run = form.is_run.data
            case.headers = form.headers.data
            case.body = form.body.data
            case.pre_case_id = form.pre_case_id.data if form.pre_case_id.data and form.pre_case_id.data != case.pre_case_id else None
            case.pre_fields = form.pre_fields.data
            case.except_result = form.except_result.data
            case.assert_type = form.assert_type.data
            case.update_time = datetime.now()
            case.is_pass = None
            case.msg = None
            case.resp = None
            try:
                db.session.commit()
                flash("保存成功", FlashEnum.success.name)
            except:
                flash("更新失败", FlashEnum.warning.name)
        else:
            form.interface.data = case.interface_id
            form.name.data = case.name
            form.is_run.data = case.is_run
            form.headers.data = case.headers
            form.body.data = case.body
            form.pre_case_id.data = case.pre_case_id
            form.pre_fields.data = case.pre_fields
            form.except_result.data = case.except_result
            form.assert_type.data = case.assert_type
            form.is_pass.data = case.is_pass
            form.msg.data = case.msg
            form.resp.data = case.resp
        return render_template("case/info.html", form=form, id=id, select=select)
    else:
        flash("您编辑的测试用例不存在", FlashEnum.warning.name)
        return redirect(url_for(".case_list"))


@case.route("/case/create/", methods=["GET", "POST"])
@login_required
def case_create():
    form = CaseAddForm()
    if request.method == "POST" and form.validate_on_submit():
        case = Case()
        interface = Interface.query.filter(Interface.id == form.interface.data).first()
        case.interface = interface

        case.service_id = interface.service_id
        case.name = form.name.data
        case.is_run = form.is_run.data
        case.headers = form.headers.data
        case.body = form.body.data
        case.pre_case_id = form.pre_case_id.data if form.pre_case_id.data else None
        case.pre_fields = form.pre_fields.data
        case.except_result = form.except_result.data
        case.creater_id = current_user.id
        case.assert_type = form.assert_type.data
        case.create_time = datetime.now()
        case.update_time = datetime.now()
        try:

            db.session.add(case)
            db.session.commit()
            flash("创建成功", FlashEnum.success.name)
        except:
            flash("创建失败", FlashEnum.warning.name)
        return redirect(url_for(".case_list"))
    else:
        return render_template("case/add.html", form=form, select=select)


@case.route("/case/<id>/copy/", methods=["POST"])
@login_required
def case_copy(id):
    try:
        case = Case.query.get(id)
        new_case = Case()
        new_case.service_id = case.service_id
        new_case.interface_id = case.interface_id
        new_case.name = case.name + "--复制"
        new_case.is_run = case.is_run
        new_case.headers = case.headers
        new_case.body = case.body
        new_case.pre_case_id = case.pre_case_id
        new_case.pre_fields = case.pre_fields
        new_case.except_result = case.except_result
        new_case.assert_type = case.assert_type
        new_case.creater_id = case.creater_id
        new_case.update_time = datetime.now()
        new_case.create_time = datetime.now()
        db.session.add(new_case)
        db.session.commit()
        flash("复制成功", FlashEnum.success.name)
    except:
        flash("由于字段过 or 数据库连接失败长导致复制失败", FlashEnum.danger.name)
    return redirect(url_for(".case_list"))


@case.route("/case/delete/", methods=["POST"])
@login_required
def case_delete():
    id = request.form.get("id")
    case = Case.query.get(id)
    if case:
        db.session.delete(case)
        db.session.commit()
        flash("删除成功", FlashEnum.success.name)
    return redirect(url_for(".case_list"))


@case.route("/case/<id>/run/", methods=["POST"])
@login_required
def case_run_by_id(id):
    is_pass, msg = case_run.run_case(id)
    if is_pass == "success":
        flash(msg, FlashEnum.success.name)
    else:
        flash(msg, FlashEnum.warning.name)
    if request.form.get("from_type") == "from_list":
        return redirect(url_for(".case_list"))
    return redirect(url_for(".case_info", id=id))


@case.route("/case/quick_search/", methods=["POST"])
@login_required
def case_quick_search():
    case_form = CaseSearchForm()
    cases = Case.query.filter(Case.creater_id == current_user.id).order_by(Case.update_time.desc())
    name = request.form.get("name")
    if name:
        cases = [case for case in cases if case.name.find(name) != -1]
        case_form.name.data = name
    return render_template("case/list.html", cases=cases, form=case_form, select=select)

app/templates/case/add.html
{% extends 'base_ext.html' %}
{% block title %}新建测试用例{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('case.case_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
    </div>

    <div class="info-body">
        <form action="{{ url_for('case.case_create') }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>

    {#============长页面埋点导航============#}
    <div class="quick-point">
        <ul>
            <li>快速导航...</li>
            <li><a href="#main">回到顶部</a></li>
            <li><a href="#request-header">请求体(body)</a></li>
            <li><a href="#request-pre-fields">前置数据</a></li>
        </ul>
    </div>
{% endblock %}

app/templates/case/info.html
{% extends 'base_ext.html' %}
{% block title %}测试用例详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-info.css') }}">

{% endblock %}
{% block selection %}
    <div class="case-selection">
        <ul class="case-selection-list">
            <li>| 快速导航...</li>
            <li>| <a href="#content-body">回到顶部</a></li>
            <li>| <a href="#request-header">请求体(body)</a></li>
            <li>| <a href="#request-pre-fields">前置数据</a></li>
        </ul>
    </div>
{% endblock %}
{% block main %}
    <div class="info-func-btn">
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('case.case_list') }}">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </button>
            </div>
        </form>
        <form class="navbar-form navbar-left" role="search" action="{{ url_for('case.case_run_by_id',id=id) }}"
              style="margin-left: 30px" method="post">
            <div class="form-group btn-right">
                <button type="submit" class="btn btn-danger">调试</button>
            </div>
        </form>
    </div>
    <div class="info-body">
        <form action="{{ url_for('case.case_info',id=id) }}" method="post">
            <div class="form-container">
                {{ wtf.quick_form(form) }}
            </div>
        </form>
    </div>

    {#============长页面埋点导航============#}
    <div class="quick-point">
        <ul>
            <li>快速导航...</li>
            <li><a href="#main">回到顶部</a></li>
            <li><a href="#request-header">请求体(body)</a></li>
            <li><a href="#request-pre-fields">前置数据</a></li>
        </ul>
    </div>
{% endblock %}

app/templates/case/list.html
{% extends 'base_ext.html' %}
{% block title %}测试用例一览{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base-list.css') }}">
{% endblock %}
{% block main %}
    <div class="list-top">
        <div class="list-top-search">
            <form class="navbar-form navbar-left" role="search" action="{{ url_for('case.case_list') }}" method="post">
                {{ wtf.quick_form(form) }}
            </form>
        </div>
        <div class="list-top-func-btn">
            <li>
                <a href="{{ url_for("case.case_create") }}">
                    <button type="submit" class="btn btn-primary">新建用例</button>
                </a>
            </li>
        </div>
    </div>
    <div class="list-body">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                {% for th in ["编号","服务名称","所测接口","测试用例名称","是否执行","调试结果","更新时间"] %}
                    <th>{{ th }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for case in cases %}
                <tr class="tr-td">
                    <td class="td">{{ case.id }}</td>
                    <td class="td"><a
                            href="{{ url_for('services.service_info',id=case.service.id) }}">{{ case.service.name }}</a>
                    </td>
                    <td class="td"><a
                            href="{{ url_for('interface.interface_info',id=case.interface.id) }}">{{ case.interface.name }}</a>
                    </td>
                    <td class="td">{{ case.name }}</td>
                    {% if case.is_run=="Yes" %}
                        <td class="td"><span class="label label-primary">是</span></td>
                    {% else %}
                        <td class="td"><span class="label label-default">否</span></td>
                    {% endif %}
                    {% if case.is_pass=="success" %}
                        <td class="td"><span class="label label-success">成功</span></td>
                    {% elif case.is_pass=="fail" %}
                        <td class="td"><span class="label label-danger">失败</span></td>
                    {% else %}
                        <td class="td"></td>
                    {% endif %}
                    <td class="td">{{ case.update_time }}</td>
                    <td class="padding-0px">
                        <form action="{{ url_for('case.case_info',id=case.id) }}" class="form-container">
                            <button class="btn btn-primary">详情</button>
                        </form>
                    </td>
                    <td class="padding-0px">
                        <form action="{{ url_for('case.case_delete') }}" class="form-container" method="post">
                            <input type="text" name="id" style="display: none" value="{{ case.id }}">
                            <button class="btn btn-danger">删除</button>
                        </form>
                    </td>
                    <td class="padding-0px">
                        <form action="{{ url_for('case.case_copy',id=case.id) }}" class="form-container" method="post">
                            <button class="btn btn-success">复制</button>
                        </form>
                    </td>

                    <td class="padding-0px">

                        <form action="{{ url_for('case.case_run_by_id',id=case.id) }}" class="form-container"
                              method="post">

                            <input type="text" name="from_type" style="display: none" value="from_list">
                            <button class="btn btn-danger">调试</button>
                        </form>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}